name: Static code analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff radon vulture pytest
          npm install -g jscpd

      - name: Run static checks
        run: bash scripts/run_static_checks.sh

      - name: Upload static reports
        uses: actions/upload-artifact@v4
        with:
          name: static-reports
          path: reports/**
